### ISSUE TITLE
LG D800 briked after flashing bootstack-d800-LP_30d-loki-signed

### ISSUE THREAD

**Issue by armujahid** [lg-devs/bootstacks#5]
I was using stock lollipop D80030F with stock bootloader and baseband ends with 128. After flashing bootstack-d800-LP_30d-loki-signed via TWRP, my phone turns off on LG logo. After connecting it with pc I found out that my phone is in detected as qhsusb_bulk mode so I have to re flash aboot, recovery etc

**Comment by Rashed97** [comment]
Yes. That's to be expected. When using stock KitKat or lollipop, you have
to use a 4.4 or 5.0 aboot. The loki baseband uses a 4.2 aboot. Use the bump
version next time, though I don't know why you want to use this if you're
on stock.

**Comment by armujahid** [comment]
I was trying to flash BlisPop. I have found this bootstack from this post http://forum.xda-developers.com/showpost.php?p=57807747&postcount=2

**Comment by Rashed97** [comment]
Still, stock will not boot with these bootstacks

**Comment by Suprabat** [comment]
I used the bumped version, I managed to flash to CM12.1, but since then I got the "secure booting error" upon booting into recovery. I tried the method in http://forum.xda-developers.com/showthread.php?t=2582142&page=1, and successfully pushed everything, but still have the same secure booting error. I wonder if anybody is experiencing the same issue.
